### PR TITLE
added logging to skip

### PR DESCRIPTION
**Pull request by rileyscool**

### CODE REVIEW

**Review by igorwastaken — COMMENTED** [review]
Thank you, please, I recommend that you learn more about queues and tracks by accessing the [website](https://discord-player.js.org/) of the package used in the project.

**Comment by rileyscool** [comment]
> Thank you, please, I recommend that you learn more about queues and tracks by accessing the [website](https://discord-player.js.org/) of the package used in the project.

ok but that wont work

**Comment by xWass** [comment]
> > Thank you, please, I recommend that you learn more about queues and tracks by accessing the [website](https://discord-player.js.org/) of the package used in the project.
> 
> ok but that wont work

your mother wont work

**Comment by xWass** [comment]
sorry ill stop

**Pull request merged**
