### PR TITLE
Update playing.js

### PR DESCRIPTION
**Pull request by rileyscool**

### CODE REVIEW

**Comment by igorwastaken** [comment]
Duplicate of #12 lmfao

**Comment by rileyscool** [comment]
> Duplicate of #12 lmfao

no its not i changed

**Comment by igorwastaken** [comment]
@rileyscool pls redo this pr?

**Comment by rileyscool** [comment]
> @rileyscool pls redo this pr?

why

**Comment by rileyscool** [comment]
its fixed now so i dont need to

**Comment by igorwastaken** [comment]
Conflicts

**Pull request closed without merging**
